src/aten/sycl/Loops.h, src/aten/sycl/MemoryAccess.h, src/aten/sycl/MemoryAccessUtils.h, test/python/examples/test_loops.py
Optimized loops backbone, includes:
1. Used global range stride kernel instead of legacy kernel for no-cast case.
2. For broadcast case, we vectorized it wherever possible.
3. Reduce the number of loops kernels.
4. Add UTs.
=> Enhance loops backbone

src/aten/BinaryOps.cpp, src/aten/Pow.cpp, src/aten/UnaryOps.cpp, src/aten/sycl/BinaryKernels.cpp, src/aten/sycl/BinaryKernels.h, src/aten/sycl/BinaryRemainderKernel.cpp, src/aten/sycl/BinaryRemainderKernel.h, src/aten/sycl/PowKernels.cpp, src/aten/sycl/PowKernels.h, src/aten/sycl/UnaryKernels.cpp, src/aten/sycl/UnaryKernels.h, src/aten/sycl/UnaryLogKernels.cpp, src/aten/sycl/UnaryLogKernels.h, test/python/examples/test_binary.py, test/python/examples/test_unary.py, yaml/xpu_functions.yaml
1. Complement ATen operators' variants implementation.
2. Add new Binary operators, e.g. rsub, remainder, fmod, reciprocal, pow.
dep on: https://github.com/intel/torch-xpu-ops/pull/42
=> Complement ATen operators' variants with `func`, `inplace` and `out`.

cmake/BuildFlags.cmake, cmake/Modules/FindSYCL.cmake
At the current stage, enable AOT compilation only for PVC. On the other platforms, JIT works with generic SPIRV.
=> Enable AOT compilation

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/documentation.yml, .github/ISSUE_TEMPLATE/feature-request.yml
In this PR, we just port pytorch issue templates here as this repo is part of PyTorch and cannot be built w/o pytorch.
=> Add issue templates for bug and rfc submission

src/aten/UnaryOps.cpp
Note [Complex abs and angle] Complex inputs to abs and angle return float results by default. abs and angle, in both NumPy and C++, returns a float result when given a complex input. This makes sense mathematically since the absolute value and angle of a complex number has no imaginary part.
=> Fix abs complex to float issue

test/xpu/test_ops.py
1. Fix bugs of "name 'Sequence' is not defined" in test suite.
2. Retrieve abs in testing list.
=> FIx bugs of "name 'Sequence' is not defined" in test suit

src/aten/Pow.cpp
1. Apply type promotion for pow ops.
2. Apply borrowing output for pow ops.
=> Rebase aten::pow with creating borrowing output and using type promotion

.github/workflows/pull.yml, examples/test_torchvision_roi_align.py, src/aten/NMS.cpp, src/aten/XPUFallback.template
1. Avoid dangling operator's implementation (m.impl(torchvision::nms) is ahead of `import torchvision` sometime)
2. Mute debug log of explicit CPU fallback.
3. Add torchvision.roi_align/_roi_align_backward example case
=> Register operator's implementation lazily.

.github/workflows/inductor_xpu_e2e_ci.yml
As oneDNN GEMM has not supported FP64 yet, we fallback the benchmark to CPU fp64
=> Enable fp64 tmporarily

test/xpu/run_test.py, test/xpu/test_autograd_fallback.py, test/xpu/xpu_test_utils.py
Enabled test_reducations.py and test_autograd_fallback.py to run with XPU patch. Updated XPU patch for instantiate_parametrized_tests().
We did not enable skiplist in order to report failures in log.
=> Add UT for test_autograd_fallback.py

.github/workflows/pull.yml, test/xpu/run_test_with_only.py, test/xpu/run_test_with_skip.py
Some suites are too slow to go through all operators on CPU. So add a separate script to run suites with an on-demand white list. When developers add a new operator, they can easily check whether they need add related cases in run_test_with_only.py
=> Distinguish run_test.py to run with skip and run with only

test/xpu/xpu_test_utils.py
Restore the functin of instantiate_parametrized_tests in XPUPatchForImport.__exit__
=> Fixed instantiate_parametrized_tests  failed issue

test/xpu/xpu_test_utils.py
Restore the functin of instantiate_parametrized_tests in XPUPatchForImport.__exit__
=> Fixed instantiate_parametrized_tests failed issue

src/aten/BinaryOps.cpp, src/aten/sycl/BinaryDivTruncKernel.cpp, src/aten/sycl/BinaryInternal.h, src/aten/sycl/BinaryKernels.cpp, src/aten/sycl/BinaryKernels.h, src/comm/XPUMathCompat.h, test/xpu/fin_grain/run_fine_grain.py, test/xpu/run_test_with_skip.py
Fix div ut failures caused by the ineffective type promotion.
1. Align div with mul implementation by using opmath type.
2. Fix div trunc failure when result of division between two same floating point values is not 1.f sometimes.
3. Remove unnecessary kernels.
=> Fix div ut failures caused by the ineffective type promotion

.github/workflows/pull.yml, test/xpu/run_test_with_skip.py, test/xpu/test_autocast_xpu.py
refer to https://github.com/pytorch/pytorch/pull/127741, xpu autocast dtype has been switched to `float16`.
=> Change autocast dtype to float16 to make CI happy

src/aten/sycl/Indexing.cpp
Fixed test_dim_function_empty_xpu floating point exception when index is empty. See issue https.//github.com/intel/torch-xpu-ops/issues/302. Followed cpu implementation to return directly when index is empty.
=> Fix index_add issue when index is empty

src/ATen/native/xpu/sycl/UpSampleNearest1dKernels.cpp
Fixes: #475
Fixes: d0d350e ("Add aten::upsample_nearest series of ops (#373)")
```
src/ATen/native/xpu/sycl/UpSampleNearest1dKernels.cpp:278:15: warning: typedef ‘using accscalar_t = at::acc_type<double, true>’ locally defined but not used [-Wunused-local-typedefs]
278 |         using accscalar_t = acc_type<scalar_t, true>;
```
CC: @chunhuanMeng, @fengyuan14
=> build: fix warning in UpSampleNearest1dKernels.cpp

src/ATen/native/xpu/sycl/DistanceKernels.cpp, src/ATen/native/xpu/sycl/EmbeddingBag.cpp, test/xpu/run_test_with_skip.py
Incorrect max_indices returned when mode is sum or mean. Fixing inductor/test_torchinductor.py::GPUTests::test_embedding_bag_xpu.
=> [Inductor][UT failure] Fix max_indices in embedding_bag when mode is not Max

test/xpu/extended/run_test_with_skip.py
Not implemented operators, aten::_embedding_bag_backward.
To retrieve cases when the operators are supported.
https://github.com/intel/torch-xpu-ops/issues/536
"test_backward_nn_functional_embedding_bag_xpu_float32",
=> Add skip case

src/ATen/native/xpu/sycl/Col2ImKernel.cpp, src/ATen/native/xpu/sycl/Im2ColKernel.cpp, test/xpu/run_test_with_skip.py
Fixed col2im test case error: The values for attribute 'shape' do not match
=> Fixed col2im test error: The values for attribute 'shape' do no match

src/ATen/native/xpu/XPUFallback.template, test/xpu/run_test_with_skip.py
PyTorch enforced unused-function and unused-variable compilation options recently. It leads to torch-xpu-ops building failure with -Werror.
Fixing: https://github.com/pytorch/pytorch/pull/130084
=> build: fix -Wunused-function warning

src/ATen/native/xpu/sycl/MultinomialKernel.cpp, src/CMakeLists.txt
Including 1. libtorch_xpu.so (Host only, operator level) 2. libtorch-xpu-ops-sycl-ker-partx.so (Device code) libtorch-xpu-ops-sycl-ker-partx.so at most includes 50 SYCL kernel related source files, will be about 1GB.
=> Split binary of PyTorch XPU operators into multiple libraries

src/ATen/native/xpu/sycl/Indexing.h
We encounter an out-of-range page fault for the index put kernel. This is because the condition check order is not correct.
We should check the array index before accessing the array. The previous ScratchPage option of the driver may hide this issue.
Co-author:
@gaopengff
=> Fix index out of range for IndexPut kernel

test/xpu/nn/test_dropout_xpu.py, test/xpu/nn/test_multihead_attention_xpu.py, test/xpu/run_test_with_skip.py
Added hook to support xpu backend, so that test_multihead_self_attn_two_masks_fast_path_mock_xpu and test_Dropout1d_xpu and test_Dropout3d_xpu can pass.
=> add hook for _check_arg_device2 and freeze_rng_state to support xpu

test/xpu/run_test_with_skip.py
RuntimeError: Double and complex datatype matmul is not supported in oneDNN
=> Add skip cases

cmake/Modules/FindSYCL.cmake
`SYCL_LIBRARIES` contains duplicate path of sycl libraries.
=> Fix duplicate sycl libraries

test/xpu/run_test_with_skip.py
The feature is enabled by https://github.com/pytorch/pytorch/pull/129864.
=> upsample_bilinear: Enabled deterministic cases

src/ATen/native/xpu/XPUFallback.template
Fixes: #640
Fixes: 6eca394 ("Add aten::nextafter and its variants")
CC: @fengyuan14 @yucai-intel @xytintel
=> Drop CPU fallback for aten::norm.out and aten::nextafter.out

cmake/BuildFlags.cmake, cmake/Modules/FindSYCL.cmake, cmake/Modules/FindSYCLToolkit.cmake, cmake/SYCL.cmake, src/ATen/CMakeLists.txt, src/ATen/native/xpu/sycl/AmpKernels.cpp, src/CMakeLists.txt, test/sycl/CMakeLists.txt
Support XPU ABI neutral build.
Starting from compiler 2025.0, `libsycl.so` is ABI-neutral lib. Before this, the `libsycl-preview.so` is ABI-neutral.
refer to https://github.com/pytorch/pytorch/pull/130110
=> Support XPU ABI=0 build

src/ATen/native/xpu/NMS.cpp, src/ATen/native/xpu/sycl/MultiTensorApply.h, src/ATen/native/xpu/sycl/NMSKernel.cpp, src/ATen/native/xpu/sycl/Shape.cpp, src/ATen/native/xpu/sycl/SoftMaxKernels.cpp, src/ATen/native/xpu/sycl/TriangularOpsKernels.cpp
The un-templated data_ptr() does not check about the type check and storage_initialized() check. Thus, it may introduce potential bugs.
By using the template data_ptr, this could throw an error like below:
```
torch._dynamo.exc.TorchRuntimeError: Failed running call_function torchvision.roi_align(*(FakeTensor(..., device='xpu:0', size=(1, 1024, 50, 75), dtype=torch.bfloat16), FakeTensor(..., device='xpu:0', size=(1000, 5), dtype=torch.bfloat16), 0.0625, 14, 14, 0, True), **{}):
The tensor has a non-zero number of elements, but its data is not allocated yet. Caffe2 uses a lazy allocation, so you will need to call mutable_data() or raw_mutable_data() to actually allocate memory.
```
=> Use safe API to access Tensor data pointer

src/ATen/xpu/EmptyTensor.cpp, src/ATen/xpu/EmptyTensor.h, src/CMakeLists.txt
Expose TORCH_XPU_API to Pytorch
=> Expose TORCH_XPU_API to Pytorch

test/xpu/run_test_with_skip.py, test/xpu/test_nn_xpu.py
This fixes issues from #653
The case is verifying an expected assertion log raised in kernel. We have different log in XPU backend, different keyword (we have no 'CUDA'), different index (we are using work item).
Original test case uses CUDA specific calls, and expected assert message returned from CUDA. The test cases are now rewritten in `test_nn_xpu.py` to adapt to XPU specific counterparts.
- "test_cross_entropy_loss_2d_out_of_bounds_class_index_xpu_float16",
- "test_cross_entropy_loss_2d_out_of_bounds_class_index_xpu_float32",
=> unittest: make test_cross_entropy_loss_2d_out_of_bounds_class_index compatible for XPU

src/ATen/native/xpu/sycl/Reduce.h
Remove reduce workaround since using `xpu::pair` directly.
=> Remove reduce workaround since using xpu::pair directly

test/xpu/run_test_with_skip.py, test/xpu/test_modules_xpu.py
Remove unnecessary cases from skip list after evaluating https://github.com/intel/torch-xpu-ops/issues/256
=> unittest: Remove skips from skip list

src/ATen/native/xpu/sycl/Reduce.h
Fixing: https://github.com/intel/torch-xpu-ops/issues/611 (test_min_xpu_bool)
Tracking: https://github.com/intel/torch-xpu-ops/issues/698
Another change: Aligning memory access utility `c10::load` with PyTorch usage, `c10::load` makes bool data with value compatible.
=> mtl: reduction: Bypass group reduction on SLM by sparing workload to other SGs when SIMD=8

test/xpu/run_test_with_skip.py
We enabled PTI for Kenito Profiler XPU backend. The case fails. We retrieve the case once the bug is fixed.
Tracking: https://github.com/intel/torch-xpu-ops/issues/731
=> Skip TestAutograd.test_profiler temporarily

test/xpu/extended/run_test_with_skip.py, test/xpu/extended/test_ops_xpu.py, test/xpu/skip_list_common.py, test/xpu/test_decomp_xpu.py, test/xpu/test_torch_xpu.py, test/xpu/xpu_test_utils.py
fix some accuracy problems.
1. add decorator `toleranceOverride` to opinfo when hooking opdb. This method can handle the cases with accuracy problems wrapped by `ops`. (except the difference is nan or inf)
2. fix test_decomp, test_torch accuracy problem.
3. align lastest pytorch code of  `ModuleTest_test` "test_Conv2d_dilated_with_long_tensor_cuda", "test_Conv2d_groups_thnn_with_long_tensor_cuda", "test_Conv2d_groups_with_long_tensor_cuda", "test_Conv2d_no_bias_with_long_tensor_cuda", "test_Conv2d_padding_with_long_tensor_cuda", "test_Conv2d_strided_with_long_tensor_cuda", "test_Conv2d_with_long_tensor_cuda", "test_Conv3d_1x1x1_no_bias_with_long_tensor_cuda", "test_Conv3d_groups_with_long_tensor_cuda", "test_Conv3d_no_bias_with_long_tensor_cuda", …
=> adjust tolerance for xpu in utils (#749)

test/xpu/skip_list_common.py
skiped the cases due to pytorch uplift, see #809.
=> skip failed cases due to #809

test/xpu/xpu_test_utils.py
filter double, complex128, float64 from the dtypeIfXPU and dtype_backward of op for ARC.
=> filter fp64 dtypes for ARC

test/xpu/skip_list_common.py
skiped the cases due to pytorch uplift, see #809.
=> skip failed cases due to #809 

src/ATen/native/xpu/Copy.cpp, src/ATen/native/xpu/Resize.cpp, src/ATen/native/xpu/Sorting.cpp, src/ATen/native/xpu/UnaryOps.cpp, src/ATen/native/xpu/sycl/ActivationGeluKernel.cpp, src/ATen/native/xpu/sycl/Atomics.h, src/ATen/native/xpu/sycl/BinaryRemainderKernel.cpp, src/ATen/native/xpu/sycl/Math.h, src/ATen/native/xpu/sycl/Pow.h, src/ATen/native/xpu/sycl/PowKernels.cpp, src/ATen/native/xpu/sycl/Reduce.h, src/ATen/native/xpu/sycl/SoftMaxKernels.cpp, src/ATen/native/xpu/sycl/Sorting.cpp, src/ATen/native/xpu/sycl/SortingCommon.h, src/ATen/native/xpu/sycl/SortingRadixSelect.h, test/xpu/extended/run_test_with_skip.py
e.g. We use `std::log` instead of `::log` because `::log` always introduces FP64 instructions regardless of the input data type.
=> Using std math templates instead of functions

src/ATen/native/xpu/Copy.cpp, src/ATen/native/xpu/Resize.cpp, src/ATen/native/xpu/Sorting.cpp, src/ATen/native/xpu/UnaryOps.cpp, src/ATen/native/xpu/sycl/ActivationGeluKernel.cpp, src/ATen/native/xpu/sycl/Atomics.h, src/ATen/native/xpu/sycl/BinaryRemainderKernel.cpp, src/ATen/native/xpu/sycl/Math.h, src/ATen/native/xpu/sycl/Pow.h, src/ATen/native/xpu/sycl/PowKernels.cpp, src/ATen/native/xpu/sycl/Reduce.h, src/ATen/native/xpu/sycl/SoftMaxKernels.cpp, src/ATen/native/xpu/sycl/Sorting.cpp, src/ATen/native/xpu/sycl/SortingCommon.h, src/ATen/native/xpu/sycl/SortingRadixSelect.h, test/xpu/extended/run_test_with_skip.py
e.g. We use `std::log` instead of `::log` because `::log` always introduces FP64 instructions regardless of the input data type.
=> Using std math functions (cmath) instead of C math functions (math.h)

src/ATen/native/xpu/Normalization.cpp
Align the semantic of accumulate type in the renorm operator with stock PyTorch.
=> Align the semantic of accumulate type in the renorm operator with stock PyTorch

test/xpu/xpu_test_utils.py
Add hook to avoid the case failures on ARC by avoid creating float64 input:
test_ops_xpu.py::TestCommonXPU::test_compare_cpu_cat_xpu_bfloat16 can pass with hook to reference_inputs_cat()
test_ops_xpu.py::TestCommonXPU::test_compare_cpu_index_put_xpu_bfloat16  with hook to index_variable()
test_ops_xpu.py::TestCommonXPU::test_compare_cpu_log_softmax_with_dtype_xpu_bfloat16 with hook to sample_inputs_softmax_variant()
=> add hook to avoid fp64 issues in input

src/ATen/native/xpu/sycl/UnaryKernels.cpp
Resolve the FP64 issue in the expm1 operator on ARC.
=> expm1: Align data type in computation with class definition

test/xpu/xpu_test_utils.py
To avoid the following issues on ARC:
FAILED test_ops_xpu.py::TestCommonXPU::test_compare_cpu_log_softmax_with_dtype_xpu_bfloat16 - RuntimeError: Kernel is incompatible with all devices in devs
--
FAILED test_ops_xpu.py::TestCommonXPU::test_compare_cpu_log_softmax_with_dtype_xpu_bool - RuntimeError: Kernel is incompatible with all devices in devs
FAILED test_ops_xpu.py::TestCommonXPU::test_compare_cpu_log_softmax_with_dtype_xpu_complex64 - RuntimeError: Kernel is incompatible with all devices in devs
FAILED test_ops_xpu.py::TestCommonXPU::test_compare_cpu_log_softmax_with_dtype_xpu_float16 - RuntimeError: Kernel is incompatible with all devices in devs
FAILED test_ops_xpu.py::TestCommonXPU::test_compare_cpu_log_softmax_with_dtype_xpu_float32 - RuntimeError: Kernel is incompatible with all …
=> enable hook to avoid fp64 issues on ARC for softmax and zeros_like

src/ATen/native/xpu/sycl/PowKernels.cpp
Fix for test_binary_ufuncs_xpu.py::TestBinaryUfuncsXPU::test_pow_xpu_float16
The previous way of casting into opmath_t leads to accuracy failure for complex half dtype on windows. This change uses memory::LoadWithCast instead which fixes the problem.
=> Fix pow operator complex32 UT failure on Windows MTL/LNL

src/ATen/native/xpu/sycl/Math.h, src/ATen/native/xpu/sycl/UnaryGammaKernels.cpp, src/comm/DeviceProperties.h, test/xpu/skip_list_arc.py
Resolve the FP64 issue in the gamma operators on ARC.
=> gamma: Align data type in computation with the declaration of the helper

test/xpu/xpu_test_utils.py
Add hooks to avoid the sample inputs on ARC.
=> Added hooks to avoid fp64 input on ARC

test/xpu/extended/run_test_with_skip_arc.py, test/xpu/extended/skip_list_arc.py, test/xpu/extended/skip_list_common.py
Add cases skip list for ARC device in extended folder.
=> Arc: Add cases skip list for extended cases

test/xpu/extended/test_ops_xpu.py
remove fp64 and complex128 test cases for ARC device in extended folder
=> remove fp64 and complex128 test cases for ARC device in extended folder

cmake/BuildFlags.cmake
Default AOT target list on Windows prefers client GPUs, including ARC, LNL and MTLs.
=> Windows: Give default AOT targets to Windows build.

src/ATen/native/xpu/sycl/DistanceKernels.cpp
The original logic only covers cases, 1) num of active sgs == 1, 2) num of active sgs > sg_size.
But doesn't cover case, num of active sgs > 1 and <= sg_size. The PR complements the logic.
=> cdist: Fix incorrect logic in reduce

test/xpu/skip_list_common.py
RuntimeError: "im2col_xpu" not implemented for 'Bool'
Will retrieve cases once we support bool in im2col_xpu.
=> unittest: Skip new failures due to PyTorch uplift

.github/workflows/_linux_ut.yml, .github/workflows/nightly_ondemand.yml, .github/workflows/nightly_ondemand_rolling.yml, .github/workflows/nightly_ondemand_whl.yml, .github/workflows/pull.yml
Recently, we found that the Linux kernel version may affect the result. This PR adds kernel information for CI jobs:
1. For UT, I changed to use `python torch/utils/collect_env.py`. It will print the necessary info. 
2. For E2E test, added the `KERNEL_VERSION` column in the report.
Related PR: https://github.com/pytorch/pytorch/pull/135828
=> [CI] Print Kernel information for CI jobs

src/ATen/CMakeLists.txt
Export `<ATen/xpu/EmptyTensor.h>` to public (the counterpart location of CUDA is `${AT_INSTALL_INCLUDE_DIR}/ATen/cuda`） as it is used in codegen, refer to https://github.com/pytorch/pytorch/pull/130082/files#r1696016201
Otherwise, IPEX finds it hard to reuse this codegen due to the non-exist file of `<ATen/xpu/EmptyTensor.h>`.
The same reason applies to libtorch, which is one pure C++ code.
=> Export EmptyTensor.h to public

test/xpu/skip_list_common.py, test/xpu/test_autograd_xpu.py
1. Fixed cuda hardcode for autograd UT.
2. Skiped unsupport ops for XPU device.
issue report in:
https://github.com/intel/torch-xpu-ops/issues/821
https://github.com/intel/torch-xpu-ops/issues/814
=> Fixed cuda hardcode for autograd UT and skip unsupport UT for xpu

.github/workflows/nightly_ondemand.yml
Fixes the On-demand Test has no Kernel version output.
=> [CI] Fix no output of KERNEL_VERSION for on demand test

src/ATen/native/xpu/sycl/UniqueKernels.cpp
To fix the unique issues in https://github.com/intel/torch-xpu-ops/issues/922. 
test_meta_xpu.py::TestMetaXPU::test_dispatch_meta_outplace_unique_consecutive_xpu_bfloat16 PASSED                                                                                                                              [  4%]
test_meta_xpu.py::TestMetaXPU::test_dispatch_meta_outplace_unique_consecutive_xpu_bool PASSED                                                                                                                                  [  8%] 
test_meta_xpu.py::TestMetaXPU::test_dispatch_meta_outplace_unique_consecutive_xpu_float16 PASSED                                                                                                                               [ 13%] …
=> unique_consecutive: rebase with enabling kBFloat16

src/ATen/native/xpu/ForeachOpList.cpp, src/ATen/native/xpu/ForeachOpScalar.cpp, src/ATen/native/xpu/ForeachOpScalarList.cpp, src/ATen/native/xpu/ForeachUnaryOp.cpp, src/ATen/native/xpu/Nonzero.cpp, src/ATen/native/xpu/RangeFactories.cpp, src/ATen/native/xpu/sycl/ActivationGluKernels.cpp, src/ATen/native/xpu/sycl/ForeachTernaryKernels.cpp, src/ATen/native/xpu/sycl/PointwiseOpsKernels.h, src/ATen/native/xpu/sycl/PowKernels.cpp, src/ATen/native/xpu/sycl/ReduceNormKernel.cpp, src/ATen/native/xpu/sycl/Sorting.cpp, src/bridge.cpp
1. Taking forward-declaration from PyTorch exposed headers not rewriting them.
2. Formating coding style.
=> foreach: Format codes for slow path

test/xpu/skip_list_common.py, test/xpu/test_type_promotion_xpu.py
For https://github.com/intel/torch-xpu-ops/issues/890, all test passed except some sparsity cases in skip list.
=> Enable test_type_promotion.py

test/xpu/xpu_test_utils.py
`max.dim` and `min.dim` have already been impelmented, but their uts have not been added to the test scope.
=> Add uts of  `max` and `min`

test/xpu/xpu_test_utils.py
Fix histogram ut failure caused by incorrect threshold settings.
=> Fix histogram ut failure caused by incorrect threshold settings

src/ATen/native/xpu/LayerNorm.cpp, src/ATen/native/xpu/UpSample.h
Accroding to https://github.com/pytorch/pytorch/pull/138364 to use `[[maybe_unused]]` to suppress the unused warning.
Maybe it could fix the [issue](https://github.com/intel/torch-xpu-ops/issues/987) introduced by https://github.com/intel/torch-xpu-ops/pull/770/files#diff-ae810fb2aff5cf37ab1b21244fd1e172a660a8e4f4b9292f0661af64c2f92b21L15.
=> Use [[maybe_unused]] to suppress unsued warning

yaml/native/native_functions.yaml
- `lerp_.Scalar`
- `lerp_.Tensor`
Delegates to structured ops `lerp.Scalar_out` and `lerp.Tensor_out` respectively. The corresponding kernels `xpu::lerp_scalar_kernel` and `xpu::lerp_tensor_kernel` are already implemented.
=> Add aten::lerp_

test/xpu/skip_list_common.py
UT cases failed for CUDA graph：
test_foreach_xpu.py::TestForeachXPU::test_big_num_tensors__foreach_max_use_cuda_graph_True_w_empty_False_xpu_float32
test_foreach_xpu.py::TestForeachXPU::test_big_num_tensors__foreach_max_use_cuda_graph_True_w_empty_False_xpu_float64
test_foreach_xpu.py::TestForeachXPU::test_big_num_tensors__foreach_max_use_cuda_graph_True_w_empty_True_xpu_float32
test_foreach_xpu.py::TestForeachXPU::test_big_num_tensors__foreach_max_use_cuda_graph_True_w_empty_True_xpu_float64
test_foreach_xpu.py::TestForeachXPU::test_big_num_tensors__foreach_norm_use_cuda_graph_True_w_empty_False_xpu_float32
test_foreach_xpu.py::TestForeachXPU::test_big_num_tensors__foreach_norm_use_cuda_graph_True_w_empty_False_xpu_float64
test_foreach_xpu.py::TestForeachXPU::test_big_num_tensors__foreach …
=> skip cases which used CUDA graph

CMakeLists.txt
Directly caused by CXX flag `-Werror`:
```bash
oneapi/compiler/2025.0/bin/compiler/../../include/sycl/detail/builtins/builtins.hpp:235:1: error: multi-line comment [-Werror=comment]
// clang++ -[DU]__SYCL_DEVICE_ONLY__ -x c++ math_functions.inc  \
```
=> Prevent building errors caused by SYCL compiler

src/ATen/native/xpu/sycl/Indexing.cpp
For issue https://github.com/intel/torch-xpu-ops/issues/1053, verified with the test:
=> Enable FP8 for aten::index_select

src/ATen/native/xpu/sycl/EmbeddingBag.cpp, src/ATen/native/xpu/sycl/EmbeddingBag.h
Resolve issue: https://github.com/intel/torch-xpu-ops/issues/1052
Ref: https://github.com/pytorch/pytorch/blob/aaefa484417a84a2f5cfcfe4d5041b596c074b4c/aten/src/ATen/native/cuda/EmbeddingBag.cu#L89
=> Add boundary check for `embedding_bag` operator

CMakeLists.txt
Warnings are generated within the SYCL library when using the OneAPI compiler, so `-Wno-error` is used to prevent failures when the `WERROR` flag is enabled.
=> Eliminate `Werror` flag to prevent building failures on Linux

src/ATen/native/xpu/sycl/LossCTCKernels.cpp, test/xpu/test_nn_xpu.py
Resolve https://github.com/pytorch/pytorch/issues/140781
=> CTCLoss: Fix the hang issue caused by barrier divergence

test/xpu/skip_list_common.py
As we enhanced XPU operator coverage, some UTs in `test_torch_xpu.py` can be enabled.
=> Update skip list in `test_torch_xpu`

src/ATen/native/xpu/sycl/Indexing.h
Resolve issue: https://github.com/intel/torch-xpu-ops/issues/1048
=> Fix `index_with_sort` kernel accuracy error with nonstandard bool dtype

src/ATen/native/xpu/sycl/MultiTensorApply.h, test/xpu/test_binary_ufuncs_xpu.py
Fix the bug where shared memory initialization is missing in the foreach backbone
=> Add sycl convention invocation in MultiTensorApplyKernelFunctor

.github/scripts/apply_torch_pr.py, .github/scripts/env.sh, .github/workflows/_linux_ut.yml, .github/workflows/nightly_ondemand.yml, .github/workflows/nightly_ondemand_rolling.yml, .github/workflows/nightly_ondemand_whl.yml, cmake/BuildFlags.cmake, src/ATen/native/xpu/sycl/MultiTensorApply.h, src/ATen/native/xpu/sycl/ScatterGatherKernels.cpp, src/BuildOnWindows.cmake, test/xpu/test_binary_ufuncs_xpu.py
Reset to https://github.com/intel/torch-xpu-ops/commit/bfdbaf444042b21f72f40f1fc22ab30a44bd0ffb
=> Sync main into release/2.6 branch

src/ATen/native/xpu/sycl/ActivationSoftshrinkKernels.cpp, src/ATen/native/xpu/sycl/GroupNormKernels.cpp
Primarily adopt vectorization approaches for `GroupNormForward` kernel.
=> Fix the low performance issue in `GroupNorm` kernels

src/ATen/xpu/EmptyTensor.cpp
Fix https://github.com/pytorch/pytorch/issues/140877
Some PyTorch C++ users could call empty op directly. In this situation, lazy initialization would not have been triggered. So we have to add `lazyInitDevice` here, which also aligns with CUDA [convention](https://github.com/pytorch/pytorch/blob/150ffb6e07f3802f8d0d3e843486e77a872803cf/aten/src/ATen/cuda/EmptyTensor.cpp#L13).
=> Support lazy initialization for empty_xpu

src/ATen/native/xpu/sycl/DilatedMaxPool2d.cpp, src/ATen/native/xpu/sycl/DilatedMaxPool2d.h
Fix: https://github.com/intel/torch-xpu-ops/issues/938
=> Reuse the max op implemented by the reduction kernel to optimize the global max pooling

src/ATen/native/xpu/sycl/ActivationSoftshrinkKernels.cpp, src/ATen/xpu/EmptyTensor.cpp
- [add lazy init for empty_xpu](https://github.com/intel/torch-xpu-ops/pull/1115)
- [nan propagation for soft_shrink](https://github.com/intel/torch-xpu-ops/pull/1116/files#diff-b7cb5876d000db957286c8b0e72badb2b7502402c8955334f1cc21c34c98a5b9)
=> [Release-2.6] Fix bugs of `empty_xpu` and `soft_shrink`

src/ATen/native/xpu/DilatedMaxPool2d.cpp, src/ATen/native/xpu/sycl/DilatedMaxPool2d.cpp
The dispatch of `at::max_outf` was originally at the kernel level, move it to the op level.
Another impact is, before the commit, build of torch-xpu-ops happens to fail due to missing dependency between CodeGen and Kernel lib in CMake.
=> MaxPool: Move the redispatch of fast path to operator level.

.github/actions/inductor-xpu-e2e-test/action.yml, .github/scripts/apply_torch_pr.py, .github/scripts/env.sh, .github/workflows/_linux_ut.yml, .github/workflows/nightly_ondemand_whl.yml
1. Additional PRs apply script for windows
2. Checkout the corresponding torch & torch-xpu-ops versions for wheel tests
3. Don't need source DL-Essential for nightly wheel tests
=> Optimize preci & ngihtly tests

test/xpu/extended/skip_list_arc.py, test/xpu/extended/skip_list_common.py, test/xpu/skip_list_common.py, test/xpu/test_unary_ufuncs_xpu.py
1.Extend UT test_nonzero_static_large to XPU device.
2. Skip some cases for rounding/trunc div accuracy.
3. Skip some cases for unspport tunableop.
=> Extend UT test_nonzero_static_large to XPU device and skip some cases

.github/workflows/_linux_transformers.yml
Annotations are available on a summary page of executed workflow.
=> ci: print annotations for key package versions in transformers test

.github/scripts/apply_torch_pr.py, src/ATen/native/transformers/SDPUtils.cpp
Fixing building error related to the patch: https://github.com/pytorch/pytorch/pull/129735.
Apply https://github.com/pytorch/pytorch/pull/143739 for replacement.
=> Apply new tolerance modification patch for E2E

.github/scripts/apply_torch_pr.py, src/ATen/native/transformers/SDPUtils.cpp, src/ATen/native/xpu/sycl/LerpKernels.cpp
solve issue https://github.com/intel/torch-xpu-ops/issues/1200
=> [Release/2.6] Fix torch.lerp RuntimeError when weight is CPU scalar while input & end are XPU tensor

test/xpu/extended/run_test_with_skip_bmg.py, test/xpu/extended/run_test_with_skip_lnl.py, test/xpu/extended/run_test_with_skip_mtl.py, test/xpu/extended/skip_list_win_bmg.py, test/xpu/extended/skip_list_win_lnl.py, test/xpu/extended/skip_list_win_mtl.py, test/xpu/run_test_with_skip_bmg.py, test/xpu/run_test_with_skip_lnl.py, test/xpu/skip_list_win_bmg.py, test/xpu/skip_list_win_lnl.py
Add skip lists for LNL, BGM and MTL devices
=> Add skip lists for LNL, BGM and MTL devices

test/xpu/skip_list_common.py
1. Skip float8 dtype UT cases
2. workaround: skip some cases because UT random failure
=> Skip float8 dtype UT cases and workaround

src/ATen/native/xpu/sycl/BatchNormKernels.cpp
When to implement a kernel for all shapes with vectorized LD/ST, we have to handle non-aligned head (base address) and short tail (tail < vector size). Before the commit, there was lack of head handling which leaded to non-vector-size-aligned vectorized ST.
The fixing enforces shapes for vectorize path. The vectorized kernel could be called only in the case in which feature dim could be divided by vector size. There will always be aligned head and exact tail.
=> Fix batch norm vectorize path accuracy issue by enforcing shape alignment

src/ATen/native/xpu/sycl/BatchNormKernels.cpp
When to implement a kernel for all shapes with vectorized LD/ST, we have to handle non-aligned head (base address) and short tail (tail < vector size). Before the commit, there was lack of head handling which leaded to non-vector-size-aligned vectorized ST.
The fixing enforces shapes for vectorize path. The vectorized kernel could be called only in the case in which feature dim could be divided by vector size.
=> [Release/2.6] Fix batch norm vectorize path accuracy issue by enforcing shape alignment

.github/workflows/pull.yml
Update windows CI label set so that only the PR that sets a specific label 'windows_ci' will trigger windows CI.
=> [CI] Update windows CI label set

.github/workflows/nightly_ondemand.yml, .github/workflows/nightly_ondemand_rolling.yml, .github/workflows/nightly_ondemand_whl.yml
Cause Inductor UTs are not good now, temporarily skip the relevant cases, and add them later when the cases are healthy.
=> [Regular test] [UT scope] Temp skip inductor UT scope for regular tests

cmake/Modules/FindSYCL.cmake
=> remove useless variable in cmake

yaml/native/native_functions.yaml
=> Add trivial aten ops including `std.correction_out` and `floor_sparse_`

.github/workflows/_linux_transformers.yml
This commit introduces custom directory `.hf_home` for Transformers tests via `HF_HOME` environment variable. Currently Transformers tests populate this directory (with caches and whatever other stuff Huggingface creates) with `28G` of data. Workflow is configured to cleanup this directory after each run regardless of the test outcome.
=> ci: use custom directory in transformers workflow as HF home

yaml/native/native_functions.yaml
Device-agnostic ops. CUDA, CPU dispatched to the same ops as well. 
- `_nested_compute_contiguous_strides_offsets`
- `_nested_tensor_from_mask`
- `_nested_tensor_from_mask_left_aligned`
- `_nested_view_from_buffer`
=> Add device-agnostic NestedTensor Ops 

.github/scripts/check-transformers.py, .github/workflows/_linux_transformers.yml
Baseline is set in a python script. Script looks into the results and categorizes test cases as:
* New failures - if detected workflow is marked as failed
* New passes - if detected workflow is marked as failed (since baseline requires an update)
* Skipped flakies - if detected workflow is marked as failed (since baseline requires an update)
* Known failures - these are failing tests knowing to fail per baseline, workflow is marked as passed (if nothing from above detected)
Test cases from above categories are printed into summary.
=> ci/transformers: add baseline checks for test cases

.github/workflows/_linux_build.yml, .github/workflows/_linux_ut.yml, .github/workflows/nightly_ondemand.yml, .github/workflows/nightly_ondemand_rolling.yml, .github/workflows/pull.yml
Extract PyTorch build as a standalone job for CI/CD.
Add PyTorch build fallback mechanism to last known good commit tracked in #1280, and add a comment for new build failure.
1. created issue #1280 to track latest workable pytorch main commit 
2. ci test always pull latest pytorch main with torch-xpu-ops PR branch to build, success goto 3, failed goto 4
3. update commit in 1, continue to do ci tests
4. add comment on issue #1280 with issued pytorch commit, and read the commit in 1 and rebuild the pytorch, continue to do ci tests
=> [CI] Extract torch build as a standalone job

src/ATen/native/xpu/sycl/GroupNormKernels.cpp
When to implement a kernel for all shapes with vectorized LD/ST, we have to handle non-aligned head (base address) and short tail (tail < vector size). Before the commit, there was lack of head handling which leaded to non-vector-size-aligned vectorized ST.
The fixing enforces shapes for vectorize path. The vectorized kernel could be called only in the case in which feature dim could be divided by vector size. There will always be aligned head and exact tail.
=> Fix group norm vectorize path accuracy issue by enforcing shape alignment

src/ATen/native/xpu/sycl/StepKernels.cpp
Resolve https://github.com/intel/torch-xpu-ops/issues/1169
=> Improve bfloat16 accuracy of `nextafter` kernel

src/ATen/native/xpu/sycl/Indexing.cpp
Replace `__restrict__` with macro `RESTRICT` to maintain cross platform compatibility.
=> Fix keyword restrict to fix Windows Build

src/ATen/native/xpu/sycl/StepKernels.cpp
Resolve https://github.com/intel/torch-xpu-ops/issues/1169
=> Improve bfloat16 accuracy of `nextafter` kernel (step2)

src/ATen/native/xpu/sycl/BatchNormKernels.cpp
Add vectorization implementations of batch norm backward kernels, with speeding up by up to 1.27x for channels-last cases and 1.32x for normal cases.
=> Introduced vectorized batch norm backward kernels

test/xpu/nn/test_init_xpu.py, test/xpu/skip_list_common.py, test/xpu/test_comparison_utils_xpu.py, test/xpu/test_native_functions_xpu.py, test/xpu/test_torch_xpu.py, test/xpu/xpu_test_utils.py
To fix https://github.com/intel/torch-xpu-ops/issues/1343. 
1. The definition of AMPERE_OR_ROCM is changed in pytorch tests and become cuda specific. - Add hook for it.
2. We should not hook torch.cuda.is_available in XPUPatchForImport because some API would depend on the return value of this interface, for example _get_device_index
3. Recovered some test classes removed by lintrunner -a
=> fix import errors and type errors in UT

.github/scripts/lintrunner.sh, tools/linter/clang_tidy/generate_build_files.py
With the following command, lintrunner.sh will do a cmake-only build and call torchgen to create xpu files under pytorch/build/xpu, then will call lintrunner to check CLANGTIDY and CLANGFORMAT for xpu related cpp and .h code.
```
export ADDITIONAL_LINTRUNNER_ARGS="--take CLANGTIDY,CLANGFORMAT build/xpu/**/*.* build/xpu/*.* third_party/torch-xpu-ops/src/*.* third_party/torch-xpu-ops/src/**/*.* third_party/torch-xpu-ops/src/**/**/*.* third_party/torch-xpu-ops/src/**/**/**/*.*"
export CLANG=1
bash third_party/torch-xpu-ops/.github/scripts/lintrunner.sh
```
=> Enable CLANGTIDY AND CLANGFORMAT lint check

src/comm/DeviceProperties.h
Tested with copy_() operator and ran a ResNet-50 on PVC to verify the functionality.
=> [Hotfix] Manually adjust the vector width for vectorized kernel

src/ATen/native/xpu/sycl/GroupNormKernels.cpp
- Apply adaptive kernel config for `group_norm_forward`.
- Fix pointer misalignment relevant bugs
=> Apply adaptive kernel config for vectorized `group_norm` forward kernels

.github/workflows/_linux_build.yml, .github/workflows/_windows_ut.yml, cmake/ONEMKL.cmake, src/ATen/native/xpu/SpectralOps.cpp
- Turn off USE_ONEMKL by default before this feature matures.
- Fix `_fft_c2c_xpu_out` fallback.
- Set `USE_ONEMKL=1` in torch-xpu-ops CI.
=> Turn off USE_ONEMKL by default

.github/ci_expected_accuracy/inductor_timm_models_inference.csv, .github/ci_expected_accuracy/inductor_timm_models_training.csv, .github/ci_expected_accuracy/inductor_torchbench_inference.csv, .github/ci_expected_accuracy/inductor_torchbench_training.csv
According to latest weekly https://github.com/intel/torch-xpu-ops/actions/runs/13332933285
1. levit_128 https://github.com/pytorch/pytorch/pull/145112
2. hf_Reformer https://github.com/intel/torch-xpu-ops/issues/1262
3. nvidia_deeprecommender https://github.com/intel/torch-xpu-ops/issues/1260
4. yolov3 pytorch pinned torchbench upgraded to 373ffb19dc470f4423a3176a4133f8f4b3cdb5bd
5. soft_actor_critic https://github.com/intel/torch-xpu-ops/issues/1273
6. Super_SloMo amp_bf16 passed
=> Update passed models and fixed issues

.github/scripts/check-transformers.py, .github/workflows/_linux_transformers.yml
Adding 3 changes:
* Use shared print environment action
* Always print not implemented ops (even on failing workload)
* Add one more flaky test to the list for better ci stability
=> ci: update transformers workload

CMakeLists.txt, cmake/Modules/FindXCCL.cmake, cmake/XCCL.cmake
We need to update `USE_XCCL` back to PyTorch to facilitate https://github.com/pytorch/pytorch/pull/147161
=> Update USE_XCCL back to PyTorch

src/ATen/native/xpu/sycl/BatchNormKernels.cpp
We don’t need to vectorize FP32 currently.
=> Change `batch_norm` vectorization policy

src/ATen/native/xpu/sycl/DilatedMaxPool3d.cpp
Use a more appropriate workgroup size and use registers to optimize performance
=> Optimize Maxpooling forward/backward: Use a more appropriate workgroup size and use registers to optimize performance

test/regressions/test_torchvision_roi_ops.py
Current XPU test of autocast for `roi_align` op in torchvision is failing. Recent changes in upstream torchvision change the behavior of this op for XPU when `requires_grad` is true. I have been unable to reproduce the test error locally, but will continue attempts to reproduce and fix. In the meantime, I suggest disabling the test in torch-xpu-ops for now.
=> Remove roi_align autocast test due to vision change

CMakeLists.txt
Prior to this PR, building PyTorch XPU with CCL distribution support required setting `USE_XCCL=ON USE_C10D_XCCL=ON python setup.py install`.
With this PR, it only requires `USE_XCCL=ON python setup.py install`, simplifying the process.
=> Refine XCCL build option

cmake/Codegen.cmake
Following the comments [here](https://github.com/intel/torch-xpu-ops/pull/1405#issuecomment-2693620315), this PR intend to refine code related to codegen and remove redundant code.
=> Refine codegen

src/ATen/native/xpu/NMS.cpp, src/ATen/native/xpu/sycl/NMSKernel.cpp
Based on the NMS updates in https://github.com/pytorch/vision/pull/8766, this PR moves the gather-keep section of the `nms` op from CPU to XPU. This causes a very minor slowdown for small num_boxes `< 400` but drastically increases performance for large num_boxes by eliminating data transfer between XPU and CPU. Since the number of boxes is typically `> 1000`, this is a reasonable change.
<details><summary>Details</summary>
<p>
```
XPU New Code Timings
num_boxes = 10 med = 0.60ms +- 0.10  # _batched_nms_coordinate_trick
num_boxes = 10 med = 2.73ms +- 0.04  # _batched_nms_vanilla
num_boxes = 100 med = 0.60ms +- 0.03
num_boxes = 100 med = 2.75ms +- 0.07
num_boxes = 200 med = 0.60ms +- 0.03
num_boxes = 200 med = 2.77ms +- 0.05
num_boxes = 400 med = 0.61ms +- 0.03
num_boxes = 400 med = 2.80ms …
```
=> Keep NMS on XPU 

src/BuildOnWindows.cmake
This PR addresses the issue of unnecessary static libraries (.lib files) being installed into the lib directory and subsequently included in the wheel package. Since wheel packages do not require .lib files, the related install statements have been removed to reduce the overall package size.
=> [Release/2.7] Remove unnecessary static library installation for wheel packaging

cmake/Modules/FindONEMKL.cmake
- Search libraries with explicit prefix and suffix.
- Add `mkl_sycl_blas` and `mkl_sycl_lapack`.
=> Refine oneMKL libraries linkage

CMakeLists.txt
This pr for fix use_xccl and use_c10_xccl define in pytorch raise build error
https://github.com/pytorch/pytorch/pull/147593
After pytorch pr land, we will remove torch-xpu-ops defination.
=> Fix when USE_C10D_XCCL define in pytorch will not correct update cache

cmake/BuildFlags.cmake
Add `lnl-m` to enable AOT fort LNL
=> Enable AOT fort LNL

src/ATen/native/xpu/sycl/UpSampleBilinear2dKernels.cpp, test/regressions/test_upsample_bilinear_bwd.py
We do not need to use atomic add for this op. Currently I only implement the case of align corners = True
Before: These kernels take 31ms out of 82ms in torchbench pytorch_unet fp16 training.
Now they takes 2.26ms out of 51ms....
=> optimize upsample bilinear backward

.github/workflows/_linux_build.yml, .github/workflows/nightly_ondemand.yml, .github/workflows/nightly_ondemand_rolling.yml, .github/workflows/pull.yml
1. No need submodules for launch
2. Build torch commit
=> Fix build issue

CMakeLists.txt, tools/codegen/install_xpu_headers.py
1. fix codegen path on Windows - avoid `//` on Windows, use posix style `\` instead.
2. `USE_C10D_XCCL` is an undefined option that can't be updated by caffe2_update_option on Windows.
build pass on local Windows machine
=> fix windows build failure

cmake/Codegen.cmake
Makes sure `symlink` uses current path to `pytorch` template folder.
```
-- Found SYCL: /lus/flare/projects/Aurora_deployment/pkourdis/soft/oneapi/2025.1.0.489/compiler/2025.1/include;/lus/flare/projects/Aurora_deployment/pkourdis/soft/oneapi/2025.1.0.489/compiler/2025.1/include/sycl;/lus/flare/projects/Aurora_deployment/pkourdis/soft/oneapi/2025.1.0.489/compiler/2025.1/include/sycl (found version "20250100")
24.35.30872
-- USE_ONEMKL is set to 1
-- Compile Intel GPU AOT Targets for pvc
ln: failed to create symbolic link '/home/pkourdis/pytorch/third_party/torch-xpu-ops/yaml/templates': File exists
Please install clang-format-12 before contributing to torch-xpu-ops!
```
For instance, if you move your whole `pytorch` repo to a different directory and try to rebuild the `symlink` will be …
=> Force update symlink to pytorch templates

cmake/Codegen.cmake, tools/codegen/install_xpu_headers.py
Improve code to avoid `PermissionError` on Windows:
Previously, the script n `install_xpu_headers.py` opened the file twice - once for reading and once for writing:
```python
for file in files:
with open(file) as fr:
with open(file, "w") as fw:
```
However, on Windows, this can lead to `PermissionError` due to file access conflicts. It looks like a bug related to the Windows system or Python. I am not sure. 
To avoid this issue, we now open the file only once using `"r+"` mode, allowing both reading and writing within the same context:
```python
for file in files:
with open(file, "r+") as f:
```
Additionally, add dependencies for torch-xpu-ops codegen to ensure proper execution.
Trying to prevent writing back an unchanged file. And open the file only once to allow both reading and …
=> Improve torch-xpu-ops codegen

src/ATen/native/xpu/sycl/WelfordNorm.h
This error is unlikely to occur in isolated unit tests.
=> Fix welford norm numeric error by adding additional boundary check

src/ATen/native/xpu/SpectralOps.cpp
Fix fft_r2c for build with ONEMKL is default OFF.
=> Fix fft_r2c when not build with ONEMKL XPU

src/ATen/native/xpu/sycl/LossCTCKernels.cpp, src/ATen/native/xpu/sycl/UpSampleBilinear2dKernels.cpp, test/xpu/skip_list_common.py
fix ut  test_interpolate_bilinear_scale_2d_cuda in test _nn_xpu.py. when align corner is False, the boundary of the output image should have the scale=1. Fix the boundary condition inside kernel, it should be all points on the boundary that cannot be interpolated.
=> fix upsample bwd accuracy

src/ATen/native/xpu/Activation.cpp, src/ATen/native/xpu/Bucketization.cpp, src/ATen/native/xpu/TensorAdvancedIndexing.cpp, src/ATen/native/xpu/TensorCompare.cpp, src/ATen/native/xpu/sycl/ActivationGeluKernel.cpp, src/ATen/native/xpu/sycl/ActivationGeluKernel.h, src/ATen/native/xpu/sycl/BatchNormKernels.cpp, src/ATen/native/xpu/sycl/TensorCompareKernels.cpp, src/ATen/native/xpu/sycl/TensorCompareKernels.h
`c10::string_view` is an alias of `std::string_view` and we are planning to deprecate it.
=> Don't use c10:string_view

test/xpu/distributed/test_c10d_xccl.py
Refer https://github.com/pytorch/pytorch/pull/149144, Currently, `dist.barrier` accepts `device_ids` as a parameter that doesn't have to be a list. When `device_ids` is not provided or another value is passed, `barrier` will use the device associated with the process group at initialization to perform the synchronization.
=> Align latest dist.barrier test change

.github/workflows/_linux_accelerate.yml
* Update Accelerate to v1.6.0
* Update Transformers (in the Accelerate test) to v4.51.3
* Add concurency check to automatically abort ci jobs on new pushes to PRs
* Stop cleaning conda to avoid collisions with parallel tests running on the same system and use conda
* Create really unique conda environment to avoid collisions with parallel tests for the same workflow
Commits which added new tests (or enabled previously skipped tests) which fail:
* https://github.com/huggingface/accelerate/commit/8576112bc8d232fb7ce54ffba752851c383cfa1f
* `tests/test_big_modeling.py::BigModelingTester::test_dispatch_model_tied_weights_memory_with_nested_offload_cpu`
=> ci: update Accelerate to v1.6.0 and impove ci workflow

src/ATen/native/xpu/sycl/LayerNormKernels.cpp
The optimization mainly targets small norm dimensions. We try to reduces more idle computation resources
Test on 1550 & A100:
| shape | stride | latency(old) | latency(new) | improvement | A100 |
| --- | --- | --- | --- | --- | --- |
| bf16[25088, 16, 24] | (384, 1, 16) | 14.685ms | 0.384ms | +3824% | 1.5ms |
| bf16(1, 1024) | contig | 7.392us | 7.576us | ~= | 3.841us |
| f16(1, 1024) | contig | 6.896us | 7.216us | ~= | 3.851us |
| f32(1, 1024) | contig | 6.208us | 6.424us | ~= | 5.921us |
| bf16(2, 4096, 320) | contig | 589.648us | 589.768us | ~= | 2.691ms |
| f16(2, 4096, 320) | contig | 429.704us | 429.320us | ~= | 2.208ms |
| f32(2, 4096, 320) | contig | 402.792us | 402.816us | ~= | 2.802ms |
| bf16(512, 3136, 128) | contig | 1.251ms | 1.249ms | ~= | 1.405ms |
| f16(512, 3136, 128) | …
=> Optimize `layernom_vectorized_impl` by using adaptive wg selection

test/xpu/test_torch_xpu.py
Updates the exception type raised in a specific test case in the `test/xpu/test_torch_xpu.py` file. 
* [`test/xpu/test_torch_xpu.py`]: Updated the exception type in the `test_unflatten` method from `IndexError` to `RuntimeError` for the case where a tensor with no dimensions is unflattened.
Ref:https://github.com/pytorch/pytorch/pull/148872/files#diff-8aa1a200ec63d23db422aa31b6dca1e6cb372887c43b064ef435210b1b0dec0a
=> Update Exception Handling in test_unflatten Method for Dimensionless Tensor Case

src/ATen/native/xpu/sycl/BatchNormKernels.cpp
`c10::optional` is deprecated, use `std::optional` instead.
=> Use std::optional instead

src/ATen/native/xpu/Bucketization.cpp, src/ATen/native/xpu/ForeachReduceOp.cpp, src/ATen/native/xpu/XPUFallback.template
This PR aims to land https://github.com/pytorch/pytorch/pull/153935
=> Deprecate c10::optional, use std instead

CMakeLists.txt
Since https://github.com/pytorch/pytorch/pull/147593 is merged, `USE_XCCL` and `USE_C10D_XCCL` options are upstreamed. We should refactor them in torch-xpu-ops.
=> Refactor USE_XCCL&USE_C10D_XCCL option

.github/scripts/check-ut.py, .github/workflows/_linux_ut.yml
Upload a failure list as artifacts, the artifacts will be used by triage bot to find similar issue already reported.
=> upload ut_failure_list.csv as artifacts

.github/scripts/apply_torch_pr.py, src/ATen/native/xpu/sycl/SummaryOpsKernels.cpp, test/xpu/extended/skip_list_common.py
We decided to keep the data type consistent with the CPU for the `histc` op.
=> Support half precision compute for histc kernel

src/ATen/native/xpu/sycl/LayerNormKernels.cpp
This PR is a supplement for PR https://github.com/intel/torch-xpu-ops/pull/1635.
From the work scheduling, consider the benchmark model hf_Bert_large as an example, which utilizes a layernorm with a shape of [16, 128, 1024]. Since the vec_size is set to 4, 256 items per work group can help solve the norm operation on 1024 elements.
From the coding perspective,  the kernel implementation uses "const int n_vec_to_read = N / vec_size; " to set active items. So the item num of each work group should be  N / vec_size instead of N.
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator …
=> layernorm: supplement for adaptive wg size adjustment

.github/actions/print-environment/action.yml, .github/scripts/check-transformers.py, .github/workflows/_linux_accelerate.yml, .github/workflows/_linux_transformers.yml
Changes:
* Benchmarking scripts are pruned from Transformers by v4.49.0 due to deprecation. So we don't need to test them anymore.
* Some cuda specific tests were generalized to cover non-cuda devices which uncovered some issues.
* Some new tests were added which fail for both cuda and xpu.
* Few regressions due to changes on Transformers side
* Time required to run the test on a single system increased from around 2h to 4h
* Test split by matrix to be able to test in smaller rerunnable chunks
* Test chunks are run sequentially due to issue with parallel HF downloads
Signed-off-by: Dmitry Rogozhkin <dmitry.v.rogozhkin@intel.com>
=> ci: update Transformers to v4.51.3

src/ATen/native/xpu/SpectralOps.cpp, src/ATen/native/xpu/mkl/SpectralOps.cpp
Revert `fft_r2c` fallback after root causing the `TestInductorOpInfoXPU` failure. There is a memory layout mismatching between `aten::fft_r2c` and Inductor meta deducing. We will have another PR to correct Inductor meta deducing for XPU backend.
Inconsistent strides should be resolved in `fft_r2c` meta calculation instead of `fft_r2c` XPU kernel. The change of this PR includes:
- Reduced `_fft_r2c_mkl` overhead and simplified kernel code
- Reactivate `fft_r2c` on XPU
=> Enhanced fft_r2c overhead and reactivate fft_r2c on XPU

src/ATen/native/xpu/sycl/TriangularOpsKernels.cpp, test/regressions/test_tril.py
Fix https://github.com/pytorch/pytorch/issues/155651
Refactor the triangular operations kernels (`triu` and `tril`) for XPU in SYCL. Key changes include introducing support for element-wise operations within threads, improving memory access patterns, and simplifying the handling of tensor metadata. Additionally, redundant code has been removed for cleaner implementation.
* **Refactored `ApplyTriuTrilKernelFunctor`**:
- Added support for processing multiple elements per thread (elements_per_thread) and optimized memory access patterns (e.g., load load load load, compute compute compute compute, store store store store) to improve memory throughput.
-  Refactored offset computation to handle multi-dimensional tensors more effectively using `TensorInfo`.
- Introduced `BOOL_SWITCH` macro for …
=> Refactor Triangular Operation Kernels (triu/tril) for XPU in SYCL

src/ATen/native/xpu/mkl/BatchLinearAlgebra.cpp, src/ATen/native/xpu/mkl/SpectralOps.cpp
This PR is to refine fft and lu_solve kernels:
- Removed the unnecessary `event.wait_and_throw()` call in `_mkl_dft`, relying instead on `queue.throw_asynchronous()` for error propagation without blocking.
- Add error handling for batched LU solve operations.
=> Refine fft and lu_solve kernels on XPU device

.github/ci_expected_accuracy/lts/inductor_huggingface_training.csv, .github/ci_expected_accuracy/lts/inductor_timm_models_training.csv, .github/ci_expected_accuracy/lts/inductor_torchbench_inference.csv, .github/ci_expected_accuracy/lts/inductor_torchbench_training.csv, .github/ci_expected_accuracy/rolling/inductor_huggingface_training.csv, .github/ci_expected_accuracy/rolling/inductor_timm_models_training.csv, .github/ci_expected_accuracy/rolling/inductor_torchbench_inference.csv, .github/ci_expected_accuracy/rolling/inductor_torchbench_training.csv
Rolling: 
1. Huggingface: https://github.com/intel/torch-xpu-ops/actions/runs/15962956351
4. Torchbench inference: https://github.com/intel/torch-xpu-ops/actions/runs/15962971535
5. Torchbench training: https://github.com/intel/torch-xpu-ops/actions/runs/15962975733
6. Timm inference: https://github.com/intel/torch-xpu-ops/actions/runs/15962980575
7. Timm training: https://github.com/intel/torch-xpu-ops/actions/runs/15962983533
LTS: 
1. Huggingface and Timm: https://github.com/intel/torch-xpu-ops/actions/runs/15963156995
2. Torchbench inference: https://github.com/intel/torch-xpu-ops/actions/runs/15963160385
3. Torchbench training: https://github.com/intel/torch-xpu-ops/actions/runs/15963163938
disable_ut
=> [CI] Update accuracy reference according to pytorch 2.8 rc3 test results

src/ATen/native/xpu/sycl/Indexing.cpp, src/ATen/native/xpu/sycl/Indexing.h, test/regressions/test_index_and_index_put.py
Fix https://github.com/intel/torch-xpu-ops/issues/1751 by following methods:
- Align accumulate type selection logic with CUDA in index put deterministic kernel
- Adopt radix sort instead of merge sort
=> Improve accuracy of index put deterministic kernel

src/ATen/native/xpu/sycl/EmbeddingBag.cpp, src/ATen/native/xpu/sycl/EmbeddingBag.h
I have remove the batch kernel config so that igc will choose grf mode 128 with the sycl assert inside kernel with vec size = 8. We can now get equivalent optimization compare to previous result.
~~1. remove SYCL_KERNEL_ASSERT, this will change grf mode from 256 to 128, but there is an existing issue https://github.com/intel/torch-xpu-ops/issues/1052, I did not remove it in this pr. We should add NDEBUG flag later or use vec_size = 4~~
2. I see instruction fetch stalls because of the if branches, so move them to template params.
3. I also fixed the vectorization. Previously we actually do not enable it.
4. Previously we only use 256 threads per workgroup, but workgroup size is 1024
performance on input [409581], weight [1000000,64], offset [4096] (4096 bags), dtype = half, mode = sum
| …
=> optimize embedding bag

src/comm/DeviceProperties.h
To solve https://github.com/intel/torch-xpu-ops/issues/1121.
The original usage of `sycl::get_kernel_bundle` should not be device-specific. Since the fixing has landed on oneAPI 2025.2, kernel bundle is now created using only the kernel ID (`kid`) instead of both device and kernel ID, removing the workaround for device-specific kernel builds and associated comments.
=> Roll back to original usage of sycl::get_kernel_bundle

cmake/Codegen.cmake
Currently, XPU ATen codegen has a potential race condition. So, we need to ensure torch_cpu has been completed before starting XPU ATen codegen.
=> Fix random build failure on codegen

cmake/Codegen.cmake, src/BuildOnLinux.cmake, src/BuildOnWindows.cmake
This PR aims to ensure ATen XPU Codegen is completed before torch-xpu-ops start to build.
=> Make torch-xpu-ops build depends on ATen XPU Codegen

src/xccl/ProcessGroupXCCL.cpp, src/xccl/ProcessGroupXCCL.hpp, test/xpu/distributed/test_c10d_xccl.py
See #2076 , this is a cherry-pick for 2.9 release
This is a high impact bug, in many distributed applications this is a large memory leak resulting in OoM error (see https://github.com/intel/torch-xpu-ops/issues/2084)
=> [release/2.9] Revert tracking of Work status for FlightRecorder in ProcessGroupXCCL

.github/workflows/_linux_build.yml
=> [CI] Cleanup after build to avoid permission issue

src/xccl/ProcessGroupXCCL.cpp, src/xccl/ProcessGroupXCCL.hpp, test/xpu/distributed/test_c10d_xccl.py
The callback used to track the work status in ProcessGroupXCCL was causing an unintended memory leak by maintaining the work objects and therefor the stashed tensors. For now, I'm removing the callback and I have added a unit test to ensure this memory leak isn't returning.
Fix https://github.com/intel/torch-xpu-ops/issues/2084
=> Revert tracking of Work status for FlightRecorder in ProcessGroupXCCL 

src/ATen/CMakeLists.txt
To resolve https://github.com/intel/torch-xpu-ops/issues/2034, expose all xpu internal headers to PyTorch.
=> Install xpu internal headers to PyTorch

src/ATen/native/xpu/mkl/BatchLinearAlgebra.cpp
This PR is to fix the access to exception vector in error handling. Original implementation may cause a segmentation fault due to out-of-bounds access.
=> Fix error handling for BatchLinearAlgebra Ops
