- CMakeLists.txt
- cmake/Modules/FindSYCL.cmake
- src/CMakeLists.txt
1. Have to couple with PyTorch building process, depending on generating headers.
2. cmake `option` only supports Boolean value.
> Fixing cmake issues

- src/aten/DistributionKernels.cpp
- src/aten/sycl/DistributionKernelTemplates.h
- src/aten/sycl/DistributionKernels.cpp
- src/aten/sycl/DistributionKernels.h
- src/aten/sycl/Philox4x32.h
- test/python/examples/test_rand.py
> Add distribution operators

- test/python/examples/test_resize.py
- test/python/examples/test_unary.py
Remove "dpcpp" and “print" from test code.
> Refine coding style

- cmake/Codegen.cmake
- src/aten/XPUFallback.template
Support force fallback ops to CPU.
> Support force fallback ops to CPU

- src/aten/TensorShape.cpp
- test/python/examples/test_resize.py
The view op "aten::unfold" should not be fallback to CPU. So add the xpu implement first.
> Add unfold

- src/comm/SYCLHelpers.h
1. Add SYCL namespace alias.
2. Add 2D nd_range kernel submission helper.
> Enhance SYCL runtime helpers

- src/aten/Resize.cpp
- test/python/examples/test_resize.py
Add op aten::set_.source_Storage and aten::set_.source_Storage_storage_offset
Fix issue https://github.com/intel/torch-xpu-ops/issues/58
>  Add op aten::set_.source_Storage and aten::set_.source_Storage_storage_offset

- src/aten/BinaryOps.cpp
- src/aten/UnaryOps.cpp
- src/aten/sycl/BinaryBitwiseOpsKernels.cpp
- src/aten/sycl/BinaryBitwiseOpsKernels.h
- src/aten/sycl/UnaryKernels.cpp
- src/aten/sycl/UnaryKernels.h
- test/xpu/test_ops.py
- yaml/xpu_functions.yaml
e.g. bitwise_and, bitwise_or, bitwise_xor, bitwise_not
> Add bitwise ops

- examples/test_clamp_promotion.py
- src/aten/TensorCompare.cpp
Fix clamp type promotion error.
> Fix clamp type promotion error

- src/aten/Fill.cpp
- yaml/xpu_functions.yaml
> Add fill_.Tensor op

- src/aten/sycl/NMSKernel.cpp
Use new interface of sycl_kernel_submit for nms.
> Fix nms building error

- test/xpu/run_test.py
https://github.com/intel/torch-xpu-ops/issues/157
> Add a new skip item due to oneDNN XPU mm segfault

- .github/workflows/inductor_xpu_e2e_nightly.yml
> add fp64 into nightly

- .github/scripts/apply-torch-pr.py
fix reopen pr but code base not reverted
> fix reopen pr but code base not reverted

- .github/actions/inductor-xpu-e2e-test/action.yml
- .github/workflows/inductor_xpu_e2e_nightly.yml
> [CI] remove cpu fallback env var and extend concurrency group for ondemand test

- src/aten/TensorTransformations.cpp
- src/aten/XPUFallback.template
- src/aten/sycl/TensorTransformationsKernel.cpp
- src/aten/sycl/TensorTransformationsKernel.h
- test/xpu/fin_grain/test_ops_xpu.py
- yaml/xpu_functions.yaml
> Add flip kernel and op

- test/xpu/run_test_with_skip.py
- test/xpu/test_complex_xpu.py
Add unit test cases for complex ops.
Tests passed.
> Add unit test cases for complex ops

- test/xpu/run_test_with_only.py
- test/xpu/test_comparison_utils_xpu.py
Add unit test case for comprarison_utils ops!
Tests passed!
> Add unit test case for comprarison_utils ops

- cmake/BuildFlags.cmake
- cmake/Modules/FindSYCL.cmake
add AOT for mtlp, and fix the incorrect way to use < SYCL_OFFLINE_COMPILER_FLAGS > flag
> Add AOT build for mtl-p

- src/aten/TensorShape.cpp
Enhance compatibility of TensorShape.cpp
> Enhance compatibility of TensorShape.cpp

- src/aten/sycl/Indexing.cpp
- test/xpu/run_test_with_skip.py
- test/xpu/test_indexing_xpu.py
> Enable test_indexing (#265)

- test/xpu/nn/test_dropout_xpu.py
- test/xpu/run_test_with_skip.py
> Enable nn/test_dropout

- src/aten/sycl/CompareKernels.cpp
- test/xpu/run_test_with_skip.py
- test/xpu/test_tensor_creation_ops_xpu.py
> Enable test_tensor_creation_ops

- .github/workflows/inductor_xpu_e2e_nightly.yml
> Add nightly tests notice

- .github/workflows/inductor_xpu_e2e_nightly.yml
> fix nightly issue

- .github/workflows/inductor_xpu_e2e_nightly.yml
remove replicate input env_prepare
> fix nightly e2e workflow

- test/xpu/run_test_with_skip.py
- test/xpu/test_autograd_xpu.py
Add unit test cases for autograd ops
issue reports:
https://github.com/intel/torch-xpu-ops/issues/246
---------
> Enable test_autograd

- test/xpu/run_test_with_skip.py
- test/xpu/test_reductions_xpu.py
Add UT cases for reductions ops.
issue report: 
https://github.com/intel/torch-xpu-ops/issues/222
---------
> Enable test_reduction

- test/xpu/run_test_with_skip.py
- test/xpu/test_content_store_xpu.py
issues report:
https://github.com/intel/torch-xpu-ops/issues/267
---------
> Enable test_content_store

- test/xpu/fin_grain/run_fine_grain.py
update fine grain cases skip reason
> Evaluate fine gran cases and add comments

- .github/workflows/inductor_xpu_e2e_ci.yml
> [CI] Add release branch for e2e ci

- .github/workflows/inductor_xpu_e2e_ci.yml
- .github/workflows/inductor_xpu_e2e_nightly.yml
> modify conda env

- src/aten/Distributions.cpp
- src/aten/XPUFallback.template
- test/xpu/run_test_with_skip.py
- yaml/xpu_functions.yaml
Add aten::random_.to
Fixing: https://github.com/intel/torch-xpu-ops/issues/197
> Add variant op for random

- src/aten/Distributions.cpp
- yaml/xpu_functions.yaml
> Add bernoulli.out

- .github/actions/inductor-xpu-e2e-test/action.yml
- .github/workflows/inductor_xpu_e2e_nightly.yml
1. test report in issue 304
2. passed number check
> modify nightly check

- src/aten/XPUFallback.template
- test/xpu/run_test_with_skip.py
Including: aten::_amp_foreach_non_finite_check_and_unscale_ and aten::_amp_update_scale_
> Add CPU fallback for GradScaler

- src/aten/ReduceOps.cpp
- src/aten/XPUFallback.template
- src/aten/sycl/BinaryMiscBackwardOpsKernels.h
- src/aten/sycl/ReduceLogicKernel.cpp
- src/aten/sycl/ReduceOpsKernels.h
- src/aten/sycl/UnarySignKernels.cpp
- test/xpu/fin_grain/test_ops_xpu.py
- yaml/xpu_functions.yaml
Including aten::all.dim, aten::all.out, aten::all.dims, aten::all.dims_out, aten::all, aten::all.all_out aten::any.dim, aten::any.out, aten::any.dims, aten::any.dims_out, aten::any and aten::any.any_out.
> Add aten::all/any and their variants

- test/xpu/nn/test_pruning_xpu.py
- test/xpu/run_test_with_only.py
> Enable test_pruning

- .github/scripts/apply_torch_pr.py
add deterministic PR into PR list
> Enable deterministic for mkldnn ops

- test/xpu/test_dataloader_xpu.py
Rewrite test case for "test_nested_tensor_multiprocessing" since it is hard code for cuda.
> Fixed ut case error for test_dataloader_xpu.py

- src/ATen/native/sparse/SparseCsrTensor.cpp
- src/ATen/native/sparse/SparseTensor.cpp
Fixed https://github.com/intel/torch-xpu-ops/issues/585
> Fix debug build

- src/ATen/native/xpu/EmbeddingBag.cpp
- test/xpu/extended/run_test_with_skip.py
- yaml/xpu_functions.yaml
https://github.com/intel/torch-xpu-ops/issues/536
> Enable aten::_embedding_bag_backward

- src/ATen/native/xpu/RangeFactories.cpp
- src/ATen/native/xpu/ReduceOps.cpp
- src/ATen/native/xpu/sycl/AveragePool2dKernels.cpp
- src/ATen/native/xpu/sycl/BatchNormKernels.cpp
- src/ATen/native/xpu/sycl/BinaryDivFloorKernel.cpp
- src/ATen/native/xpu/sycl/BinaryDivTruncKernel.cpp
- src/ATen/native/xpu/sycl/BinaryMiscBackwardOpsKernels.cpp
- src/ATen/native/xpu/sycl/DistanceKernels.cpp
- src/ATen/native/xpu/sycl/DistributionTemplates.h
- src/ATen/native/xpu/sycl/Dropout.cpp
- src/ATen/native/xpu/sycl/EmbeddingBackwardKernel.h
- src/ATen/native/xpu/sycl/EmbeddingBag.cpp
- src/ATen/native/xpu/sycl/GroupNormKernels.cpp
- src/ATen/native/xpu/sycl/LayerNormKernels.cpp
- src/ATen/native/xpu/sycl/LossNLL2dKernels.cpp
- src/ATen/native/xpu/sycl/Math.h
- src/ATen/native/xpu/sycl/MultinomialKernel.cpp
- src/ATen/native/xpu/sycl/NMSKernel.cpp
- src/ATen/native/xpu/sycl/Norm.h
- src/ATen/native/xpu/sycl/PointwiseOpsKernels.cpp
- src/ATen/native/xpu/sycl/RangeFactoriesKernel.cpp
- src/ATen/native/xpu/sycl/ReduceMomentKernels.cpp
- src/ATen/native/xpu/sycl/SoftMaxKernels.cpp
- src/ATen/native/xpu/sycl/SummaryOpsKernels.cpp
- src/ATen/native/xpu/sycl/UpSampleBicubic2dKernels.cpp
- src/ATen/native/xpu/sycl/UpSampleBilinear2dKernels.cpp
- src/ATen/native/xpu/sycl/UpSampleNearest1dKernels.cpp
- src/ATen/native/xpu/sycl/UpSampleNearest2dKernels.cpp
Use `at::acc_type_device` inplace of `at::acc_type`.
> Change the accumulate type interface to XPU specific

- .github/ci_expected_accuracy/inductor_torchbench_training.csv
Skip check and tracked in https://github.com/intel/torch-xpu-ops/issues/603
> Timm_regnet regression which tracked in issue 603

- src/ATen/native/xpu/Indexing.cpp
- src/ATen/native/xpu/TensorTopK.cpp
- src/ATen/native/xpu/XPUFallback.template
- src/ATen/native/xpu/sycl/RepeatKernel.cpp
- test/xpu/run_test_with_skip.py
- test/xpu/xpu_test_utils.py
- yaml/xpu_functions.yaml
> Add aten::masked_select and its variants

- src/ATen/native/xpu/AdaptiveAveragePooling2d.cpp
In inductor usage, generated Triton kernel assumes specific memory layout after compile. The fallback operator in the graph need propagate memory format correctly.
> adaptive_avgpool2d_backward: Propagate memory format correctly

- src/ATen/native/xpu/Copy.cpp
- src/ATen/native/xpu/Resize.cpp
> copy_: Align meta process of XPU implementation with PyTorch in-tree implementation

- test/xpu/run_test_with_skip.py
> skip failed cases introduced by new pytorch, #issue 746

- .github/scripts/inductor_xpu_test.sh
Fix issues https://github.com/intel/torch-xpu-ops/issues/704 & https://github.com/intel/torch-xpu-ops/issues/703
> Remove no skip for e2e test cmd

- cmake/BuildFlags.cmake
- Add AOT build option for arc device.
- Add a message if the user don't need.
> Add AOT build option for arc device

- test/xpu/extended/run_test_with_skip.py
- test/xpu/run_test_with_only.py
- test/xpu/run_test_with_skip.py
- test/xpu/run_test_with_skip_arc.py
- test/xpu/run_test_with_skip_mtl.py
- test/xpu/xpu_test_utils.py
cherry-pick https://github.com/intel/torch-xpu-ops/pull/790
> [2.5][Windows]  minor changes to support testing on windows

- test/xpu/extended/run_test_with_skip.py
- test/xpu/extended/run_test_with_skip_arc.py
- test/xpu/extended/skip_list_win.py
- test/xpu/extended/skip_list_win_arc.py
- test/xpu/skip_list_win.py
- test/xpu/skip_list_win_arc.py
Rebase https://github.com/intel/torch-xpu-ops/pull/844 with https://github.com/intel/torch-xpu-ops/pull/782, https://github.com/intel/torch-xpu-ops/pull/828
> [Windows] Enable Extended UTs

- test/xpu/xpu_test_utils.py
Update the accuracy threshold for test_out_histogram_xpu_float32.
> update threshold for histogram

- src/BuildOnWindows.cmake
Fixing loading kernel dll error.
> Windows: Build: Split kernel lib into smaller libs

- .github/workflows/nightly_ondemand.yml
- .github/workflows/nightly_ondemand_rolling.yml
- .github/workflows/nightly_ondemand_whl.yml
Fix nightly ci's issue where KERNEL_VERSION output incorrect.
> [CI] fix KERNEL_VERSION

- .gitignore
Add yaml/templates to .gitignore.
> Add yaml/templates to .gitignore

- .github/actions/inductor-xpu-e2e-test/action.yml
- .github/workflows/_linux_ut.yml
- .github/workflows/nightly_ondemand_rolling.yml
> Update tests on rolling driver

- src/ATen/native/xpu/UnaryOps.cpp
- src/ATen/native/xpu/XPUFallback.template
- src/ATen/native/xpu/sycl/UnaryComplexKernels.cpp
- src/ATen/native/xpu/sycl/UnaryComplexKernels.h
- test/xpu/xpu_test_utils.py
- yaml/native/native_functions.yaml
> Add aten::angle and its variants

- src/ATen/native/xpu/BinaryOps.cpp
- src/ATen/native/xpu/XPUFallback.template
- src/ATen/native/xpu/sycl/GcdLcmKernels.cpp
- src/ATen/native/xpu/sycl/GcdLcmKernels.h
- test/xpu/xpu_test_utils.py
- yaml/native/native_functions.yaml
> Added aten::lcm and variants.

- src/ATen/native/xpu/sycl/HistogramddKernels.cpp
- test/xpu/xpu_test_utils.py
- _histogramdd_from_bin_cts
- _histogramdd_from_bin_tensors
- _histogramdd_bin_edges
> Add aten::histogramdd variants

- test/xpu/extended/skip_list_common.py
- test/xpu/skip_list_common.py
Skip failed tests causing by PyTorch uplift.
> Skip failed tests causing by PyTorch uplift

- test/regressions/test_operation_on_device_1.py
Fix random calculation error in test_sum_on_device1 by adding device switch logic.
> Fix random calculation error in test_sum_on_device1

- test/xpu/skip_list_common.py
- test/xpu/test_distributions_xpu.py
> Enable test_distributions_xpu

- src/BuildOnLinux.cmake
- test/xpu/extended/skip_list_common.py
Fixing loading kernel dll error.
> Linux Build: Split kernel lib into smaller libs

- src/ATen/native/xpu/sycl/SortingKernels.h
- src/ATen/native/xpu/sycl/SortingRadixSort.h
- test/regressions/test_sort.py
Resolve https://github.com/intel/torch-xpu-ops/issues/1022
> Complete the logic for the AB buffer in segmented radix sort.

- src/ATen/native/xpu/RreluWithNoise.cpp
- src/ATen/native/xpu/XPUFallback.template
- src/ATen/native/xpu/sycl/GroupNormKernels.cpp
- src/ATen/native/xpu/sycl/RecordStream.cpp
- src/ATen/native/xpu/sycl/RreluWithNoiseKernels.cpp
- src/ATen/native/xpu/sycl/RreluWithNoiseKernels.h
- test/xpu/extended/skip_list_common.py
- test/xpu/skip_list_common.py
- test/xpu/test_nn_xpu.py
- test/xpu/xpu_test_utils.py
- yaml/native/native_functions.yaml
> Add aten::rrelu_with_noise and its variants

- test/xpu/nn/test_convolution_xpu.py
Add the hook to ensure deterministic=True in this case.
> add hook for test_Conv2d_deterministic_cudnn to set deterministic True

- cmake/Codegen.cmake
Add c shim wrapper codegen. 
Support generate c shim wrapper for OPs in torch_xpu_ops which extend the c shim wrapper of Pytorch in-tree XPU ops.
> Add c shim wrapper codegen.

- CMakeLists.txt
MSVC does not support `-Wno-error=comments`
> Windows building error fix

- cmake/BuildFlags.cmake
Reverts intel/torch-xpu-ops#1082
> Revert "[PT2.6][Windows] Update AOT target list on windows"

- src/ATen/native/xpu/sycl/TensorModeKernel.cpp
Resolve issue: https://github.com/intel/torch-xpu-ops/issues/1093
> Rebase tensor mode operator for avoiding SYCL intrinsics

- src/ATen/native/xpu/Sorting.cpp
- src/ATen/native/xpu/XPUFallback.template
- src/ATen/native/xpu/sycl/Sorting.cpp
- src/ATen/native/xpu/sycl/Sorting.h
- test/xpu/extended/skip_list_common.py
- test/xpu/xpu_test_utils.py
- yaml/native/native_functions.yaml
> Add aten::kthvalue

- src/ATen/native/xpu/sycl/ScatterGatherKernels.cpp
Primarily adopt better tuning for `scatter-gather` kernel launch configurations.
> Fix the low performance issue in scatter-gather kernels

- src/ATen/native/xpu/RoiAlign.cpp
- src/ATen/native/xpu/XPUFallback.template
- src/ATen/native/xpu/sycl/RoiAlignKernels.cpp
- src/ATen/native/xpu/sycl/RoiAlignKernels.h
- test/regressions/test_roi_align.py
- test/regressions/test_torchvision_roi_align.py
> Add torchvision::roi_align forward/backward

- test/xpu/skip_list_common.py
Enable the skip cases that can currently passed.
> Update the skip list

- src/ATen/native/transformers/Attention.cpp
- src/ATen/native/xpu/XPUFallback.template
- yaml/native/native_functions.yaml
As title.
To work with pytorch/pytorch#140389
> Move sdp_choice to pytorch & remove unimplemented sdpa_mem fallback

- src/ATen/native/xpu/RreluWithNoise.cpp
- src/ATen/native/xpu/sycl/RreluWithNoiseKernels.cpp
- src/ATen/native/xpu/sycl/RreluWithNoiseKernels.h
- yaml/native/native_functions.yaml
Resolve: https://github.com/pytorch/pytorch/issues/142102
> [Release-2.6] Capture rrelu_with_noise noise mutation in compile

- src/ATen/native/xpu/RreluWithNoise.cpp
- src/ATen/native/xpu/sycl/LerpKernels.cpp
- src/ATen/native/xpu/sycl/RreluWithNoiseKernels.cpp
- src/ATen/native/xpu/sycl/RreluWithNoiseKernels.h
- yaml/native/native_functions.yaml
1. Resolve: https://github.com/pytorch/pytorch/issues/142102
2. Fixing mixed device types in input Tensors of `torch.lerp`
> Capture rrelu_with_noise noise mutation in compile

- src/ATen/native/xpu/sycl/ResizeKernel.cpp
- src/ATen/xpu/EmptyTensor.cpp
> Add lazy init to empty/resize

- .github/workflows/_linux_transformers.yml
Changes:
* Add testing of tests/pipelines
* Add testing of tests/trainer
* Add printing results summary (to workload summary page)
* Add printing failure lines (to workload summary page)
Summary page contains sections in this order:
* Results summary
* Failure lines
* Annotations
> ci/transformers: add pipeline and trainer tests

- src/ATen/native/xpu/sycl/ResizeKernel.cpp
- src/ATen/xpu/EmptyTensor.cpp
As titled.
Align to CUDA.
(cherry picked from commit cd0873c40eddba4c675093898d0447b8c4e702d3)
> [Release/2.6] Add lazy init to empty/resize

- src/ATen/native/xpu/RoiAlign.cpp
- src/ATen/native/xpu/XPUFallback.template
- src/ATen/native/xpu/sycl/RoiAlignKernels.cpp
- src/ATen/native/xpu/sycl/RoiAlignKernels.h
- test/regressions/test_roi_align.py
- test/regressions/test_torchvision_roi_align.py
> [Release/2.6] Add torchvision::roi_align forward/backward

- test/xpu/skip_list_common.py
> Skip the cases for preci test

- src/ATen/native/xpu/sycl/BatchNormKernels.cpp
Resolve failures in https://github.com/intel/torch-xpu-ops/actions/runs/12501498017/job/34879100249
> [Release/2.6] Disable `batch_norm` vectorization path for accuracy consideration

- src/ATen/native/xpu/RNN.cpp
- src/ATen/native/xpu/XPUFallback.template
- src/ATen/native/xpu/sycl/RNNKernels.cpp
- src/ATen/native/xpu/sycl/RNNKernels.h
- test/xpu/skip_list_common.py
- test/xpu/xpu_test_utils.py
- yaml/native/native_functions.yaml
> [Release/2.6] Add aten::_thnn_fused_gru_cell and _thnn_fused_lstm_cell

- .github/ci_expected_accuracy/inductor_huggingface_training.csv
Issue: https://github.com/intel/torch-xpu-ops/issues/1216
> Skip DebertaV2ForQuestionAnswering training accuracy check

- test/xpu/extended/skip_list_win_mtl.py
Skip cases for workaround MTL windows PRECI test.
Will analyze it future.
> Skip cases for workaround MTL windows PRECI test

- test/xpu/extended/skip_list_win_mtl.py
Skip cases for workaround in MTL windows UT test
> Skip cases for workaround in MTL windows UT test

- test/xpu/extended/skip_list_win_mtl.py
Skip cases for workaround of MTL windows UT test
> Skip cases for workaround of MTL windows UT test

- .github/scripts/apply_torch_pr.py
https://github.com/pytorch/pytorch/pull/144450 has already been merged
> Revert apply upstream PR: pytorch#144450 

- cmake/Codegen.cmake
Resolve https://github.com/intel/torch-xpu-ops/issues/1279
> Relocate generated files to adapt to the latest design

- .github/ci_expected_accuracy/inductor_timm_models_inference.csv
- .github/ci_expected_accuracy/inductor_timm_models_training.csv
Projection of https://github.com/pytorch/pytorch/pull/145112
> Update ci_expected_accuracy for TIMM levit_128 for further investigation

- .github/workflows/_linux_ut.yml
- .github/workflows/nightly_ondemand.yml
- .github/workflows/nightly_ondemand_rolling.yml
To fix nighty whl test issue: https://github.com/intel/torch-xpu-ops/actions/runs/12869727875/job/35879197905
> [CI] Nightly whl test fix

- test/regressions/test_torchvision_roi_ops.py
- test/xpu/distributed/test_c10d_ops_xccl.py
- test/xpu/distributed/test_c10d_xccl.py
- test/xpu/run_distributed.py
I updated some code in order to pass the lintrunner with the following commands:
sudo apt-get install jq
export ADDITIONAL_LINTRUNNER_ARGS="--skip CLANGTIDY,CLANGFORMAT --all-files"
cd torch-xpu-ops
.github/scripts/lintrunner.sh
> fix lint issues in new added test code

- .github/scripts/lintrunner.sh
- .github/workflows/pull.yml
Others CI jobs will be triggered only if the lint check passed
> [CI] Enable lint check test in ci

- .github/scripts/ut_result_check.sh
Such as
2025-02-06T18:22:15.1894524Z test_nn_xpu.py,test_native_functions_xpu.py,nn/test_init_xpu.py,test_linalg_xpu.py,test_torch_xpu.py,test_comparison_utils_xpu.py,nn/test_convolution_xpu.py have failures
> Capture pytest failed

- src/ATen/native/xpu/sycl/BatchNormKernels.cpp
- src/ATen/native/xpu/sycl/WelfordNorm.h
After implementing fine-grained adjustments, a 1.18x performance speedup was achieved on ResNet50 for channels last format.
> Enhance `batch_norm` performance by fine-tuning kernel parameters

- src/ATen/native/xpu/DeformConv2d.cpp
- src/ATen/native/xpu/XPUFallback.template
- src/ATen/native/xpu/sycl/DeformConv2dKernels.cpp
- src/ATen/native/xpu/sycl/DeformConv2dKernels.h
- test/regressions/test_deform_conv.py
Add SYCL kernel for deform_conv2d op in torchvision.
> Add DeformConv2d kernel

- src/ATen/native/xpu/LinearInt4.cpp
- src/ATen/native/xpu/sycl/Dequant_int4.cpp
- src/ATen/native/xpu/sycl/LinearInt4.cpp
- test/xpu/test_linalg_xpu.py
1 Modify the layout of scale and zeropt to row-major.
2 Add more groupsize
> Modify int4 kernel scale&zp layout

- test/xpu/skip_list_common.py
Skip unspported UT for tunable ops
> Skip unspported UT for tunable ops

- .github/scripts/install_xpu.bat
- .github/workflows/_windows_ut.yml
To enable compression feature on Windows
> [CI] Upgrade DL essential version to 2025.0.1 for Windows CI

- .github/actions/pt2e/action.yml
- .github/workflows/nightly_ondemand_whl.yml
PT2E full test and the artifact is the result of test   https://github.com/kaileiyx/torch-xpu-ops/actions/runs/13968404046
> Update pt2e ASYMM and SYMM

- test/xpu/skip_list_common.py
Skip UT error cases for test_meta_xpu.py
https://github.com/intel/torch-xpu-ops/issues/1569
> Skip UT error cases for test_meta_xpu.py

- .github/workflows/_linux_accelerate.yml
- .github/workflows/_linux_transformers.yml
- .github/workflows/_linux_ut.yml
- .github/workflows/_windows_ut.yml
- .github/workflows/nightly_ondemand.yml
- .github/workflows/nightly_ondemand_rolling.yml
- .github/workflows/nightly_ondemand_whl.yml
- test/xpu/extended/run_test_with_skip.py
- test/xpu/run_test_with_only.py
- test/xpu/xpu_test_utils.py
1. UT test scope
2. UT timeout for each single case
> [Nightly] Modify UT tests scope check and single case timeout

- src/ATen/native/xpu/sycl/TensorShapeKernels.cpp
Mirror of https://github.com/pytorch/pytorch/pull/151263
> Make torch._chunk_cat support non-contiguous inputs

- .github/scripts/env.sh
To link libmkl_sycl_blas.so and libmkl_sycl_lapack.so.
> Add onemkl-sycl-blas and onemkl-sycl-lapack for CI

- test/xpu/skip_list_dist.py
> disable random failed cases

- .github/scripts/apply_torch_pr.py
- .github/workflows/_linux_op_benchmark.yml
- .github/workflows/_linux_ut.yml
- .github/workflows/nightly_ondemand.yml
- .github/workflows/nightly_ondemand_rolling.yml
- .github/workflows/nightly_ondemand_whl.yml
- .github/workflows/pull.yml
To address this issue, consider the following approaches: 
1. Add auth to use larger request limitation
2. Use git to get diff instead of Github API
> [Nightly] To fix 'requests.get too many requests'

- CMakeLists.txt
for https://github.com/pytorch/pytorch/pull/147593 pass ci
> Change option set func to make flag happy

- src/ATen/native/xpu/sycl/Loops.h
c10::guts::apply is an alias of std::apply
> Replace c10::guts::apply with std::apply 

- .github/scripts/ut_result_check.sh
- .github/workflows/_linux_ut.yml
- .github/workflows/nightly_ondemand.yml
- .github/workflows/nightly_ondemand_rolling.yml
- .github/workflows/nightly_ondemand_whl.yml
- .github/workflows/pull.yml
1. Add more unit tests for transformers from pytorch
2. Format _linux_ut.yml
> [CI] Add transformers unit tests

- .github/scripts/build.sh
Fix build issue, which will use pinned torch-xpu-ops instead of a copied
> [CI] Fix torch-xpu-ops build issue

- .github/scripts/check-ut.py
- .github/scripts/ut_result_check.sh
- .github/workflows/_linux_ut.yml
Enhance the CI process for UT cases:
- Add test/xpu/nn and test/xpu/quantization/core in UT summary and log summary function for distributed UT.
- Add filter known issue function, will skip the known failed UTs. Known ut issue list: https://github.com/intel/torch-xpu-ops/issues/1624
> [CI] Enhance UT summary and add filter known issue function

- .github/scripts/build.sh
- .github/scripts/env.sh
PyTorch related PR: https://github.com/pytorch/pytorch/pull/151899
> [BE] Upgrade XPU build packages to 2025.1 in CI & Nightly

- .github/workflows/_linux_build.yml
- .github/workflows/_linux_ut.yml
- .github/workflows/_windows_ut.yml
- .github/workflows/nightly_ondemand.yml
- .github/workflows/nightly_ondemand_rolling.yml
- .github/workflows/nightly_ondemand_whl.yml
- .github/workflows/pull.yml
Only run selected tests for CI test, by default run all tests, you can disable some of tests in description. 
Supports
disable_all
disable_ut
disable_e2e
disable_windows
> [CI] Enable CI run selected tests

- .github/workflows/_linux_accelerate.yml
- .github/workflows/_linux_build.yml
- .github/workflows/_linux_op_benchmark.yml
- .github/workflows/_linux_transformers.yml
- .github/workflows/_linux_ut.yml
- .github/workflows/_performance_comparison.yml
- .github/workflows/_windows_ut.yml
- .github/workflows/nightly_ondemand.yml
- .github/workflows/nightly_ondemand_rolling.yml
- .github/workflows/nightly_ondemand_whl.yml
- .github/workflows/pull.yml
To address security risk in workflows 
disable_windows
> [CI] Remove unnecessary token-permissions for workflow

- .github/actions/inductor-xpu-e2e-test/action.yml
- .github/scripts/apply_torch_pr.py
- .github/workflows/_linux_op_benchmark.yml
- .github/workflows/_linux_transformers.yml
- .github/workflows/nightly_ondemand.yml
1. fix windows ut issue
2. modify torchbench installation to reduce reinstalling torch
3. remove merged pr in apply_torch_pr.py
4. remove DLE source to use pypi packages _linux_op_benchmark.yml
disable_ut
disable_windows
> [Nightly] Modify nightly test workflows

- .github/scripts/apply_torch_pr.py
From https://github.com/pytorch/pytorch/pull/126516
To https://github.com/pytorch/pytorch/pull/156456
disable_ut
disable_e2e
disable_windows
> [Nightly] Update FP64 fallback PR

- .github/workflows/_linux_ut.yml
- .github/workflows/nightly_ondemand.yml
- .github/workflows/nightly_ondemand_rolling.yml
- .github/workflows/pull.yml
Use https://github.com/pytorch/pytorch/blob/main/.github/scripts/build_triton_wheel.py to build triton
disable_e2e
disable_ut
> [Nightly] Modify triton build method

- .github/scripts/check-ut.py
- .github/scripts/ut_result_check.sh
- .github/workflows/_linux_ut.yml
- test/xpu/extended/run_test_with_skip.py
- Print the new failed cases after filtered by known issue list.
- Enhance the timeout check mechanism, which helps capture the case with hang issue 
- Add UT total number summary in action summary
> [CI] Enhance the UT results check

- .github/workflows/_linux_ut.yml
- test/xpu/run_distributed.py
- test/xpu/skip_list_dist.py
> [CI] Skip distributed case failed on rolling driver

- src/ATen/native/xpu/Activation.cpp
- src/ATen/native/xpu/AdaptiveAveragePooling2d.cpp
- src/ATen/native/xpu/AdaptiveAveragePooling3d.cpp
- src/ATen/native/xpu/AdaptiveMaxPooling3d.cpp
- src/ATen/native/xpu/Col2Im.cpp
- src/ATen/native/xpu/ReflectionPad.cpp
- src/ATen/native/xpu/TensorAdvancedIndexing.cpp
- src/ATen/native/xpu/TensorFactories.cpp
- src/ATen/native/xpu/TensorShape.cpp
- src/ATen/native/xpu/XPUScalar.cpp
- src/ATen/native/xpu/sycl/AdaptiveAveragePooling2dKernels.cpp
- src/ATen/native/xpu/sycl/DilatedMaxPool2d.cpp
- src/ATen/native/xpu/sycl/LayerNormKernels.cpp
- src/xccl/FlightRecorderXCCL.cpp
- src/xccl/ProcessGroupXCCL.cpp
- src/xccl/ProcessGroupXCCL.hpp
- src/xccl/ProcessGroupXCCLMonitor.cpp
- src/xccl/ProcessGroupXCCLMonitor.hpp
> Maintain code cleanlines

- src/ATen/native/xpu/BatchLinearAlgebra.cpp
This PR refactors the LU factorization kernel for XPU devices to optimize performance and improve maintainability. The main change is the introduction of a fallback kernel for single-batch LU factorization, ensuring that the optimized MKL implementation is used only for multi-batch cases. The most important changes are:
* Added a new function `lu_factor_kernel_fallback` to handle LU factorization on CPU for cases where MKL is not used or when batch size is 1. (`src/ATen/native/xpu/BatchLinearAlgebra.cpp`)
* Updated `lu_factor_kernel_xpu` to use MKL for batch sizes greater than 1, and fallback to the CPU implementation for batch size 1 or when MKL is unavailable. (`src/ATen/native/xpu/BatchLinearAlgebra.cpp`)
> Fallback lu_factor kernel to CPU for single batch 

- .github/actions/get-runner/action.yml
- .github/actions/linux-e2etest/action.yml
- .github/actions/linux-testenv/action.yml
- .github/actions/linux-uttest/action.yml
- .github/actions/pt2e/action.yml
- .github/ci_expected_accuracy/rolling/inductor_timm_models_training.csv
- .github/workflows/_linux_e2e.yml
- .github/workflows/_linux_op_benchmark.yml
- .github/workflows/_linux_ut.yml
- .github/workflows/bisect_search.yml
- .github/workflows/nightly_ondemand.yml
- .github/workflows/pull.yml
1. use cache in container for datasets and models
2. fix np.bool8 issue in soft_actor_critic
3. fix microbench test reference issue
4. remove inductor test in nightly
5. use nightly wheel in CI if build not necessary
disable_build
> [CI] Modify test workflows
